build_mau:
  outputs:
    dev:
      account: IMIUGSY-OAB70067
      database: dev
      password: Mimzy*24
      role: ACCOUNTADMIN
      schema: analytics
      threads: 1
      type: snowflake
      user: ChetanaMuralidharan
      warehouse: compute_wh
  target: dev
pipeline_platform:
  target: dev

  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'PIPELINE_PLATFORM') }}"
      schema: DBT_DEV
      threads: 4
      client_session_keep_alive: false
